-- Adatok beszúrása
INSERT INTO classification (balance_main_group, balance_group, balance_item)
VALUES ('A', 'IMMATERIALIS_JAVAK', 'Alapítás átszervezés aktivált értéke'),
       ('A', 'IMMATERIALIS_JAVAK', 'Kísérleti fejlesztés aktivált értéke'),
       ('A', 'IMMATERIALIS_JAVAK', 'Vagyoni értékű jogok'),
       ('A', 'IMMATERIALIS_JAVAK', 'Szellemi termékek'),
       ('A', 'IMMATERIALIS_JAVAK', 'Üzleti vagy cégérték'),
       ('A', 'IMMATERIALIS_JAVAK', 'Immateriális javakra adott előlegek'),
       ('A', 'IMMATERIALIS_JAVAK', 'Immateriális javak értékhelyesbítése'),
       ('A', 'TARGYI_ESZKOZOK', 'Ingatlanok és a kapcsolódó vagyoni értékű jogok'),
       ('A', 'TARGYI_ESZKOZOK', 'Műszaki berendezések, gépek, járművek'),
       ('A', 'TARGYI_ESZKOZOK', 'Egyéb berendezések, felszerelések, járművek'),
       ('A', 'TARGYI_ESZKOZOK', 'Tenyészállatok'),
       ('A', 'TARGYI_ESZKOZOK', 'Beruházások, felújítások'),
       ('A', 'TARGYI_ESZKOZOK', 'Beruházásokra adott előlegek'),
       ('A', 'TARGYI_ESZKOZOK', 'Tárgyi eszközök értékhelyesbítése'),
       ('A', 'BEFEKTETETT_PENZUGYI_ESZKOZOK', 'Tartós részesedés kapcsolt vállalkozásban'),
       ('A', 'BEFEKTETETT_PENZUGYI_ESZKOZOK', 'Tartósan adott kölcsön kapcsolt vállalkozásban'),
       ('A', 'BEFEKTETETT_PENZUGYI_ESZKOZOK', 'Tartós jelentős tulajdoni részesedés'),
       ('A', 'BEFEKTETETT_PENZUGYI_ESZKOZOK',
        'Tartósan adott kölcsön jelentős tul. rész. viszonyban álló vállalkozásban'),
       ('A', 'BEFEKTETETT_PENZUGYI_ESZKOZOK', 'Egyéb tartós részesedés'),
       ('A', 'BEFEKTETETT_PENZUGYI_ESZKOZOK',
        'Tartósan adott kölcsön egyéb részesedési viszonyban álló vállalkozásban'),
       ('A', 'BEFEKTETETT_PENZUGYI_ESZKOZOK', 'Egyéb tartósan adott kölcsön'),
       ('A', 'BEFEKTETETT_PENZUGYI_ESZKOZOK', 'Tartós hitelviszonyt megtestesítő értékpapír'),
       ('A', 'BEFEKTETETT_PENZUGYI_ESZKOZOK', 'Befektetett pénzügyi eszközök értékhelyesbítése'),
       ('B', 'KESZLETEK', 'Anyagok'),
       ('B', 'KESZLETEK', 'Befejezetlen és félkész termékek'),
       ('B', 'KESZLETEK', 'Növendék-, hízó- és egyéb állatok'),
       ('B', 'KESZLETEK', 'Késztermékek'),
       ('B', 'KESZLETEK', 'Áruk'),
       ('B', 'KESZLETEK', 'Készletekre adott előlegek'),
       ('B', 'KOVETELESEK', 'Követelések áruszállításból és szolgáltatásból (vevők)'),
       ('B', 'KOVETELESEK', 'Követelések kapcsolt vállalkozással szemben'),
       ('B', 'KOVETELESEK', 'Követelések jelentős tul. részesedési viszonyban álló vállalkozásban'),
       ('B', 'KOVETELESEK', 'Követelések egyéb részesedési viszonyban lévő vállalkozással szemben'),
       ('B', 'KOVETELESEK', 'Váltókövetelések'),
       ('B', 'KOVETELESEK', 'Egyéb követelések'),
       ('B', 'ERTEKPAPIROK', 'Részesedés kapcsolt vállalkozásban'),
       ('B', 'ERTEKPAPIROK', 'Jelentős tulajdoni részesedés'),
       ('B', 'ERTEKPAPIROK', 'Egyéb részesedés'),
       ('B', 'ERTEKPAPIROK', 'Saját részvények, saját üzletrészek'),
       ('B', 'ERTEKPAPIROK', 'Forgatási célú hitelviszonyt megtestesítő értékpapírok'),
       ('B', 'PENZESZKOZOK', 'Pénztár, csekkek'),
       ('B', 'PENZESZKOZOK', 'Bankbetétek'),
       ('C', 'UNKNOWN', 'Bevételek aktív időbeli elhatárolása'),
       ('C', 'UNKNOWN', 'Költségek, ráfordítások aktív időbeli elhatárolása'),
       ('C', 'UNKNOWN', 'Halasztott ráfordítások'),
       ('D', 'JEGYZETT_TOKE', 'Jegyzett tőke'),
       ('D', 'JEGYZET_TOKE_BE_NEM_FIZ', 'Jegyzett, de még be nem fizetett tőke (-)'),
       ('D', 'TOKETARTALEK', 'Tőketartalék'),
       ('D', 'EREDMENYTARTALEK', 'Eredménytartalék'),
       ('D', 'LEKOTOTT_TARTALEK', 'Lekötött tartalék'),
       ('D', 'ERTEKELESI_TARTALEK', 'Értékelési tartalék'),
       ('D', 'ADOZOTT_EREDMENY', 'Adózott eredmény'),
       ('E', 'UNKNOWN', 'Céltartalék a várható kötelezettségekre'),
       ('E', 'UNKNOWN', 'Céltartalék a jövőbeni költségekre'),
       ('E', 'UNKNOWN', 'Egyéb céltartalék'),
       ('F', 'HATRASOROLT', 'Hátrasorolt kötelezettségek'),
       ('F', 'HOSSZU_LEJARATU', 'Hosszú lejáratú kötelezettségek'),
       ('F', 'HOSSZU_LEJARATU', 'Hosszú lejáratra kapott kölcsönök'),
       ('F', 'HOSSZU_LEJARATU', 'Átváltoztatható és átváltozó kötvények'),
       ('F', 'HOSSZU_LEJARATU', 'Tartozások kötvénykibocsátásból'),
       ('F', 'HOSSZU_LEJARATU', 'Beruházási és fejlesztési hitelek'),
       ('F', 'HOSSZU_LEJARATU', 'Egyéb hosszú lejáratú hitelek'),
       ('F', 'HOSSZU_LEJARATU', 'Tartós kötelezettségek kapcsolt vállalkozással szemben'),
       ('F', 'HOSSZU_LEJARATU', 'Tartós köt. jelentős tulajdoni rész. visz. lévő váll. szemben'),
       ('F', 'HOSSZU_LEJARATU', 'Tartós kötelezettségek egyéb rész. viszonyban lévő vállalkozással szemben'),
       ('F', 'HOSSZU_LEJARATU', 'Egyéb hosszú lejáratú kötelezettségek'),
       ('F', 'ROVID_LEJARATU', 'Rövid lejáratú kölcsönök'),
       ('F', 'ROVID_LEJARATU', 'Rövid lejáratú hitelek'),
       ('F', 'ROVID_LEJARATU', 'Vevőktől kapott előlegek'),
       ('F', 'ROVID_LEJARATU', 'Kötelezettségek áruszállításból és szolgáltatásból (szállítók)'),
       ('F', 'ROVID_LEJARATU', 'Váltótartozások'),
       ('F', 'ROVID_LEJARATU', 'Rövid lejáratú kötelezettségek kapcsolt vállalkozással szemben'),
       ('F', 'ROVID_LEJARATU', 'Rövid lejáratú köt. jelentős tulajdoni rész. visz. lévő váll. szemben'),
       ('F', 'ROVID_LEJARATU', 'Rövid lejáratú köt. egyéb rész.viszonyban lévő váll. szemben'),
       ('F', 'ROVID_LEJARATU', 'Egyéb rövid lejáratú kötelezettségek'),
       ('G', 'UNKNOWN', 'Bevételek passzív időbeli elhatárolása'),
       ('G', 'UNKNOWN', 'Költségek, ráfordítások passzív időbeli elhatárolása'),
       ('G', 'UNKNOWN', 'Halasztott bevételek');